### ISSUE TITLE
Move Play/Pause Button in bottom of sequencer

### ISSUE THREAD

**Issue by Babali42** [Babali42/drumbeatrepo#85]
### Problem :
The play/pause button is too far from the sequencer

### Proposed solution :
Move it just below the sequencer, it must be horizontally centered

### Wireframe of the previous idea :
![Image](https://github.com/user-attachments/assets/b4631e83-ed1a-422c-97d8-013d6fe4fd8c)

**Comment by khg051203** [comment]
Hi, I'm new to github issues, I find your issue interesting so I want to try to solve it for you, I hope you let me try this issue

**Comment by Babali42** [comment]
@khg051203 
Hi you're welcome ! Thank you for the interest you have in this project

Recently i change the sequencer header, and i think the button could be centered above the sequencer, like that

<img width="876" alt="image" src="https://github.com/user-attachments/assets/2e05a03c-3397-484c-bd87-07d8ab6576bb">

You can try to clone the repo locally, do the development and suggest a Pull Request in this repo !

**Comment by khg051203** [comment]
And now, you want to put the button above the sequencer not below sequencer ,right ?

**Comment by Babali42** [comment]
Exactly !
