### ISSUE TITLE
Add a loadbar

### ISSUE THREAD

**Issue by Babali42** [Babali42/drumbeatrepo#91]
### Problem :

When the website is waiting for rest request (load json) or media request (load sound) there is a little of latency

### Proposed solution :
Add a loadbar on these cases

- Open website
- Change genre
- Change beat

The loadbar could be above the sequencer

**Comment by GiaHuy0031** [comment]
Hi! I've created a pull request to implement the loading bar for genre and beat changes as mentioned in this issue. I look forward to your feedback!

**Comment by Babali42** [comment]
Hi ! Thanks you for the interesest in this project, and for the contribution !
I really like the use of an interceptor, i would have done something more bug prone so I'm really happy
